### ISSUE TITLE
CNAME for gh-pages with couscous?

### ISSUE THREAD

**Issue by snipe** [CouscousPHP/Couscous#105]
Hi guys - quick question - is it possible to use a CNAME file with couscous? It's publishing to my gh-pages branch as expected, but it seems to blow out my CNAME file each time I deploy. Am I missing something? (It's very possible, being that it's 3:30AM my time.)

**Comment by mnapoli** [comment]
Hi! Sorry for the late answer, was on holidays. Yes it's perfectly possible, that's what http://couscous.io and http://php-di.org use for example (e.g. here: https://github.com/CouscousPHP/Couscous/blob/master/website/CNAME)

You have to put the CNAME file in the `website/` directory though (or the template directory you configured). If you are using a default template you can't (in that case copy the template into your project).

**Comment by snipe** [comment]
Ahh, that makes sense. Would you mind if I created a PR to add that to the couscous docs? (It's obvious now that you mention it, but it might be helpful for some.)

That again for this package. It's managed to turn my FOSS project docs into a thing of beauty :)

**Comment by mnapoli** [comment]
I would definitely merge it go ahead!
