### ISSUE TITLE
Using variables in content files

### ISSUE THREAD

**Issue by romovs** [CouscousPHP/Couscous#107]
Is it possible to define variables either globally in couscous.yml or at least at the page-level using YAML front-matter and use them from within the MD files? E.g.:

couscous.yml
```
 foo: bar
```

page.md
```
<h1> {{ foo }} </h1>
```

or 

page.md
```
---
foo: bar
---

<h1> {{ foo }} </h1>
```
This might be a nice feature to have, especially for frequently updated strings which need to be reused on multiple pages.

**Comment by mnapoli** [comment]
Yes it is possible, it works in both files :)

**Comment by romovs** [comment]
Hmm I must be doing something wrong then, but the following doesn't seem to work:

couscous.yml
```foo: bar```

default.twig
```{{ content|raw }}```

page.md
```hello {{ foo }} world```

The generated page.html contains "hello {{ foo }} world" instead of "hello bar world"

**Comment by mnapoli** [comment]
Ahh sorry I didn't catch that detail: `hello {{ foo }} world` is a twig syntax, it doesn't work in Markdown. You can use the variable in Twig templates however!

**Comment by romovs** [comment]
Ah I see, thanks! 
It's a shame though, as there are many situations where certain things are just begging to be defined as 
variables; like product versions which are often repeated on multiple MD pages and tend to change frequently...

But in any case, figured out a workaround which seems to solve this - string replace on the content:

couscous.yml
```foo: bar```

default.twig
```{{ content|replace({"%%foo%%": foo })|raw }}```

page1.md
```Hello %%foo%% world```

page2.md
```Hello2 %%foo%% world2```

**Comment by mnapoli** [comment]
Nice idea. The reason it doesn't work in Markdown (and there is no plan to add it *yet*) is that it would couple you to Couscous (then the Markdown wouldn't work with any other tool).

Couscous was meant to be least intrusive, unlike other static website generators which force directory layouts, file names, custom syntax in markdown, etc. onto you. So I'm not too keen on changing that :/

**Comment by wysow** [comment]
Just my 2 cents, your solution is kind off the "official" way to do that, maybe adding it to the docs as a tip could be cool, what do you think @mnapoli?

**Comment by mnapoli** [comment]
Yep it could be great to document it!

**Comment by adrienrn** [comment]
Sorry to bring up an old question but this something that would be nice to have in couscous.

I understand your stance on decoupling markdown files from the build tools/syntax but I use this features extensively to render long and repetitive parts of the docs using `for` loops;
https://github.com/adrienrn/jquery-sheeper/blob/master/docs/index.md

Is this still something that you won't add to Couscous or did you change your mind since last year?

**Comment by mnapoli** [comment]
@adrienrn I see you are making extensive use of such features, it looks much more like a custom language than a markdown document. For that kind of needs I would use a pre-processor (that can be run automatically by Couscous with:

```yaml
scripts:
    before:
        - # command
```
