### ISSUE TITLE
Feature: Searchability?

### ISSUE THREAD

**Issue by snipe** [CouscousPHP/Couscous#110]
This may be a crazy thing to suggest, but the only (and I do mean only) thing missing from Couscous is the ability to search within the docs. Obviously, server-side tech is right out, since it's hosted on Github Pages, but what if the build process churned out a one-page file that we could feed into Javascript, which could then provide a type-ahead type of searching, where the results point to the appropriate page? 

For smaller document sets, it probably wouldn't be very useful, but for docs with a lot of files, this could be a great feature. 

For example, the docs I'm using Couscous for, http://docs.snipeitapp.com, are on the longer side, and once the user's manual gets added, they're only going to get longer. 

I've only ever seen this type of thing in generators to work from a single page .md file, though, so maybe the DOM overhead from a javascript component would be too much.

**Comment by mnapoli** [comment]
Yep it would definitely be awesome! There's already this issue about it though: #63 I will link you comment

**Comment by mnapoli** [comment]
By the way http://docs.snipeitapp.com looks really good!

**Comment by snipe** [comment]
Thanks! It's all thanks to you! <3

![tumblr_nr4wo0unyd1s373hwo1_400](https://cloud.githubusercontent.com/assets/197404/8788819/156dbda8-2ef2-11e5-898e-209169542b0d.gif)
