### ISSUE TITLE
home.twig not being loaded on custom template

### ISSUE THREAD

**Issue by sergiovilar** [CouscousPHP/Couscous#121]
Hello,

I have a `default.twig` file and a `home.twig`.
When I open the homepage couscous shows me my README into the `default.twig` layout.

What I need to do to get the `home.twig` showing in the home?

**Comment by wysow** [comment]
Hello,

I'm not sure but maybe you forgot to use this in the head of your README file:

```markdown
---
layout: home
---
```

**Comment by wysow** [comment]
You can find the documentation here: http://couscous.io/docs/templates.html#additional-layouts

**Comment by mnapoli** [comment]
:+1: that's what you need to do :)

**Comment by sergiovilar** [comment]
Oh, that's right. Works fine now, thank you!

**Comment by sergiovilar** [comment]
@mnapoli There's a way that the index webpage load another file than README.md? Maybe `docs/index.md`?

**Comment by wysow** [comment]
@sergiovilar I don't think so at the moment, as stated here: http://couscous.io/docs/faq.html#do-links-works-between-pages the README file is the `index.html` generated file, but it could be a cool feature to add... Feel free to send a PR if you wish.

**Comment by sergiovilar** [comment]
@wysow okay, thank you!!
