### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by vmayoral** [CouscousPHP/Couscous#129]
Great work with Couscous @mnapoli, seriously!.

I decided to give it a try both in Mac OS and Ubuntu but haven't been successful. My status:
- PHP is fine and activated
- `php -S localhost:8000` works ok
- `couscous preview 127.0.0.1:8000` seems to be ok:
```
couscous preview 127.0.0.1:8000
Generating /Users/Victor/Template-Light to /Users/Victor/Template-Light/.couscous/generated
Server running on 127.0.0.1:8000
```
But then when accessing that in the browser:
![captura de pantalla 2015-09-23 a las 10 04 30](https://cloud.githubusercontent.com/assets/1375246/10040300/9dd9f0c4-61da-11e5-805f-cd6eebbaed41.png)

I could use some help here.
Thanks,

**Comment by vmayoral** [comment]
@imuguruza can you verify this as well?

**Comment by mnapoli** [comment]
Hi @vmayoral, is there a README.md file in the repository you are generating? Are you using a custom template (if not sure, please show the content of your `couscous.yml`) ? Is there anything in the `/Users/Victor/Template-Light/.couscous/generated` directory? Try running simply `couscous preview` just to be sure ?

**Comment by vmayoral** [comment]
Hi @mnapoli,
>Are you using a custom template (if not sure, please show the content of your couscous.yml) 

I'm using the Template-Light sources.

>Is there anything in the /Users/Victor/Template-Light/.couscous/generated directory?

Yeap:
```
.
└── generated
    ├── LICENSE
    ├── README.md
    ├── couscous.yml
    ├── css
    │   ├── bootstrap.min.css
    │   ├── font-awesome.min.css
    │   ├── highlight.dark.css
    │   └── main.css
    ├── fonts
    │   ├── FontAwesome.otf
    │   ├── fontawesome-webfont.eot
    │   ├── fontawesome-webfont.svg
    │   ├── fontawesome-webfont.ttf
    │   └── fontawesome-webfont.woff
    └── screenshot.png

3 directories, 13 files
```

>  Try running simply couscous preview just to be sure?

```
Victor@iMac-de-Victor:~/Template-Light$ couscous preview
Generating /Users/Victor/Template-Light to /Users/Victor/Template-Light/.couscous/generated
Server running on 127.0.0.1:8000
```

**Comment by mnapoli** [comment]
Mmh I don't think this specific repository would work as a Couscous project because it's a template (quite a specific issue… because of [this line](https://github.com/CouscousPHP/Template-Light/blob/master/couscous.yml#L2) the root directory is considered to be the template, so couscous doesn't parse any markdown file there).

You might have better luck trying another repository, or even an empty directory with only a README.md file. The default template is automatically loaded by Couscous, you don't have to deal with it.

**Comment by vmayoral** [comment]
Thanks @mnapoli. Just tried https://github.com/snipe/snipe-it/tree/documentation and that did it.
