### ISSUE TITLE
"php couscous.phar preview" error "InvalidArgumentException"

### ISSUE THREAD

**Issue by natanavra** [CouscousPHP/Couscous#132]
Last lines of the cli output:

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///Users/natanavra/Desktop/couscous.phar/src/Model/WatchList/FinderWatch.php on line 21
Server running on 127.0.0.1:8000
PHP Warning:  array_map(): An error occurred while invoking the map callback in phar:///Users/natanavra/Desktop/couscous.phar/src/Model/WatchList/WatchList.php on line 39

Warning: array_map(): An error occurred while invoking the map callback in phar:///Users/natanavra/Desktop/couscous.phar/src/Model/WatchList/WatchList.php on line 39

  [InvalidArgumentException]
  "2015-11-01 08:31:49" is not a valid date.

**Comment by mnapoli** [comment]
Hi, the first warning was reported in #119 and fixed. I have just released a new version (1.3.2), could you try with this version and tell me if it's working better?
