### ISSUE TITLE
[Windows] bash: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by cyberbit** [CouscousPHP/Couscous#136]
More Windows problems, I'm afraid.

I recently did a clean install of Windows 10 to solve some ongoing problems with my laptop. I restored most of the original apps and data to their original locations, but some are still not installed as I haven't needed them yet.

In any case, running `php "C:\Users\djmar\OneDrive\Development\Web\Couscous\couscous.phar" deploy -v` fails at GitHub login:
```
Deploying the website
Cloning https://github.com/cyberbit/modation.git in C:\Users\djmar\AppData\Local\Temp\couAAEE.tmp
Checking out branch gh-pages
Copying generated website
Committing changes
warning: LF will be replaced by CRLF in docs/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in index.html.
The file will have its original line endings in your working directory.
Pushing gh-pages (GitHub may ask you to login)



  [Couscous\CommandRunner\CommandException]
  bash: /dev/tty: No such device or address
  error: failed to execute prompt script (exit code 1)
  fatal: could not read Username for 'https://github.com': Invalid argument



Exception trace:
 () at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/src/CommandRunner/CommandRunner.php:29
 Couscous\CommandRunner\CommandRunner->run() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/src/CommandRunner/Git.php:61
 Couscous\CommandRunner\Git->run() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/src/CommandRunner/Git.php:44
 Couscous\CommandRunner\Git->push() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/src/Deployer.php:118
 Couscous\Deployer->pushBranch() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/src/Deployer.php:56
 Couscous\Deployer->deploy() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/src/Application/Cli/DeployCommand.php:106
 Couscous\Application\Cli\DeployCommand->execute() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://C:/Users/djmar/OneDrive/Development/Web/Couscous/couscous.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at C:\Users\djmar\OneDrive\Development\Web\Couscous\couscous.phar:52
```
I had previously installed MinGW and Cygwin (which aren't installed at the moment), which could be the problem. I'll update here as I learn more.

**Comment by cyberbit** [comment]
**Update**: Looks like pulling the old "run `git push origin gh-pages` in the temp directory" trick works, interestingly:
```
C:\Users\djmar\AppData\Local\Temp\couAAEE.tmp>cd C:\Users\djmar\AppData\Local\Temp\couDB76.tmp

C:\Users\djmar\AppData\Local\Temp\couDB76.tmp>git push origin gh-pages
Username for 'https://github.com': cyberbit
Password for 'https://cyberbit@github.com': hahayoucantseeit:P
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 478 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
To https://github.com/cyberbit/modation.git
   e19c9bb..3e8ec0c  gh-pages -> gh-pages
```
I tried this command twice, it pushed the site correctly both times. Couscous had the same problem (same stack trace) both times as well.

**Comment by mnapoli** [comment]
Sounds like the `git push` command is failing because it can't get a tty to let you input your username/password :/

**Comment by cyberbit** [comment]
@mnapoli But what does that *mean*? :P Am I doing something wrong? Do you have an idea of what might cause that kind of error? My thought is a network configuration problem on my computer, perhaps a firewall. I'll do some more testing and see if that's the case.

**Comment by mnapoli** [comment]
I have no idea. The git command is run by `exec` (see here: https://github.com/CouscousPHP/Couscous/blob/master/src/CommandRunner/CommandRunner.php#L24), that seems to fail to bind a tty on Windows.

**Comment by mnapoli** [comment]
Maybe it's worth trying replacing `exec` by another command like `passthru`, or trying to figure out why it doesn't work on Windows. I did a quick search yesterday and couldn't find anything useful.

**Comment by avargaskun** [comment]
@cyberbit I was running into the same problem. Using the advice from [this other post](https://github.com/atom/atom/issues/8984#issuecomment-165722062) fixed it for me:

> Try adding this into your git config

```
[credential]
    helper = wincred
```

**Comment by wysow** [comment]
@cyberbit can we close this one if @avargaskun trick is working for you?

**Comment by cyberbit** [comment]
@wysow Certainly, but I'll have to try it first. I'll update once I test later today.

**Comment by cyberbit** [comment]
@wysow Looks like that's worked wonderfully, thanks for the solution!

**Comment by SMILEORIGIN** [comment]
I add the text "[credential]
    helper = wincred" in the config but it also cant't run 
Please tell me why? I take 2days to make hexo + github blog,I'm so tired

**Comment by wysow** [comment]
@SMILEORIGIN can you provide more info so we can help, where did you add the
```
[credential]
    helper = wincred
```
snippet?

What is exactly your error message?

And if the error message is different from the one in the first message of this thread, please open a new issue.

And thanks for trying out Couscous.

**Comment by eliranmal** [comment]
this issue stems from [an issue on git-for-windows][1]


[1]: https://github.com/git-for-windows/git/issues/327
