### ISSUE TITLE
Tests are broken on windows

### ISSUE THREAD

**Issue by Zolli** [CouscousPHP/Couscous#143]
Hi,

tried to run test suite on windows, unit test suite works correctly, but integration tests is broken.
Quick look on this, the biggest problem is hardoced `/` characters. I try to submit a pull request for this if found some time.

**Comment by mnapoli** [comment]
Thank you, a PR would be most welcome indeed.

**Comment by bobmulder** [comment]
Can be resolved by defining an `DS` (directory seperator) and using it...

```
if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
```

Now use `DS` instead of `/`

**Comment by mnapoli** [comment]
I'm going to close this issue as I don't consider it a bug with Couscous itself and there are other tickets about Windows support. Feel free to make a pull request to make test run on Windows.
