### ISSUE TITLE
Add Couscous to Awesome-php

### ISSUE THREAD

**Issue by bobmulder** [CouscousPHP/Couscous#145]
Probably Couscous should be added to the documentation-section of the awesome-php list: https://github.com/ziadoz/awesome-php#documentation

I didnt want to create a PR because I don't know if the owner agreed ;) So it's just a suggestion!

**Comment by wysow** [comment]
Seems legit for me so :+1: ;)

**Comment by mnapoli** [comment]
I'm definitely +1, FYI there is this PR: https://github.com/ziadoz/awesome-php/pull/329 But since it has conflicts, it might be worth creating another *and* adding Couscous to the list of documentation tools (not static website generators) as you suggested.

**Comment by bobmulder** [comment]
Let me know if you want me to create one ;)

**Comment by mnapoli** [comment]
Yep go ahead!

**Comment by bobmulder** [comment]
Just created a PR: https://github.com/ziadoz/awesome-php/pull/586

**Comment by mnapoli** [comment]
Done! thanks @bobmulder
