### ISSUE TITLE
Pages aren't rebuild if their contents are unchanged but the menu contents change

### ISSUE THREAD

**Issue by JonathanMace** [CouscousPHP/Couscous#151]
I'm using couscous for a project site here: http://brownsys.github.io/tracing-framework
I've tweaked one of the out-of-the box templates and I'm using it here: https://github.com/jonathanmace/pivottemplate

I'm in the process of writing and deploying the documentation for my project.  This consists of writing some pages, deploying them, writing some more pages, deploying them, and so on.  When I redeploy the site, most of the .md files are completely unchanged from the previous deploy.   But since I'm in the process of adding extra pages, my menu structure in the couscous.yml file has changed, which means the html for every page needs to be regenerated with the new menu.

It appears that couscous is not currently doing this.  It seems to only check whether the .md file has updated, and doesn't handle the case where the .md file is unchanged but the menu structure differs.

**Comment by wysow** [comment]
Hello @JonathanMace and thanks for trying Couscous!

I just tried to update the menu items on the Couscous website itself locally and it worked as expected... (but please note that there is **no** live reload so you need to manually refresh the browser tab)

But there is also a static menu for Couscous website on top of the page which is set directly in template files, and therefore can't be updated, maybe that's the case for you too?

To be sure that the `couscous.yml` menu is used, you should be using this kind of stuff in your templates:

```twig
<ul class="nav nav-pills nav-stacked">
    {% for itemId, item in menu.items %}
        <li class="{{ itemId == current_menu ? 'active' }}">
            <a href="{{ item.absoluteUrl|default(baseUrl ~ '/' ~ item.relativeUrl) }}">
                {{ item.text|raw }}
            </a>
        </li>
    {% endfor %}
</ul>
```

I'm available if you have some questions.

**Comment by mnapoli** [comment]
> This consists of writing some pages, deploying them, writing some more pages, deploying them, and so on. When I redeploy the site…

I'm confused you are specifically talking about `couscous deploy` here? I.e. when you deploy some pages are not rebuilt with the new menu? Do you get the same thing when using `couscous preview` locally?

**Comment by JonathanMace** [comment]
I don't get the same behavior when I use couscous preview; this is only when I'm using couscous deploy.

**Comment by mnapoli** [comment]
I can see only one commit in the `gh-pages` branch in your repository: https://github.com/brownsys/tracing-framework/commits/gh-pages Did you generate the website more than once?

**Comment by JonathanMace** [comment]
I've been deleting the branch before deploying each time.

I just typed this up, and tried it:

> I just added a new page, docs/test.md, and also added it to the menu structure.  I redeployed with `couscous deploy`.  If you visit the page I just added, you see it in the menu structure: http://brownsys.github.io/tracing-framework/docs/test.html. But if you click any of the previous links, the test page disappears from the menu.

However, as it turns out, the test page did correctly appear in the menu everywhere when I cleared my browser cache.  Chalk this one up to stupidity on my part.

Thanks for the responses @mnapoli @wysow

**Comment by mnapoli** [comment]
:+1: glad to know
