### ISSUE TITLE
No travis-auto-deploy without PHP-Version

### ISSUE THREAD

**Issue by UFOMelkor** [CouscousPHP/Couscous#152]
When running `vendor/bin/couscous travis-auto-deploy` I'm getting this error: `This version of the documentation is already deployed`

It does not appear when I execute `vendor/bin/couscous travis-auto-deploy --php-version $TRAVIS_PHP_VERSION` instead.
I guess it's because of the [default PHP version that is assumed](https://github.com/CouscousPHP/Couscous/blob/f36e5a72acacadc4b95ee8c130b96b947fe2e90a/src/Application/Cli/TravisAutoDeployCommand.php#L65).
Perhaps skipping the check when no PHP version has been passed might be a better strategy?

**Comment by wysow** [comment]
Hello @UFOMelkor and thanks for trying Couscous!

We made php 5.4 as the default value as it's the minimum required version of php for Couscous as set [in composer.json](https://github.com/CouscousPHP/Couscous/blob/master/composer.json#L18).

So if your project is using another php version you should be using the `php-version` option to set default version. When Travis runs are set on multiple php version they can be executed in parallel so we need this option with a default value to avoid multiple deploys.

If it does not seems right to you, feel free to add a comment.

**Comment by UFOMelkor** [comment]
Sorry, my fault. I assumed that the `--php-version` must be set only if travis runs with multiple PHP versions. Thank you for clarification and for this great tool. I love it :+1:

**Comment by wysow** [comment]
NP, always better to ask!
