### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by bobmulder** [CouscousPHP/Couscous#167]
Since GitLab supports [GitLab Pages](http://docs.gitlab.com/ee/pages/README.html), I would love to use CousCous there... 

I have no idea if there changes needed to get this working... Any ideas on this?

**Comment by wysow** [comment]
Seems like http://docs.gitlab.com/ee/pages/README.html#how-.gitlab-ci.yml-looks-like-when-using-a-static-generator is a good starting point, if your project does have Couscous as dev dependency that could be doable.

Then just using it in the Gitlab configuration file like said in the documentation should do the trick.

Maybe just try it and come back with more detailed problems/errors if any... ;)

**Comment by mnapoli** [comment]
:+1: maybe it works out of the box, after all Couscous only pushed changes in a `gh-pages` branch so if you use the branch Gitlab is expecting that should do it.

**Comment by bobmulder** [comment]
I'll try when needed ;) closing for now and I'll put some feedback in time ;) Looking at @mnapoli his answer, it should work...
