### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by bobmulder** [CouscousPHP/Couscous#176]
I've been trying to create a website which took me too much time because I had to install all kinds of dependencies. Is there a docker image available to get started easily?

**Comment by mnapoli** [comment]
Hi, I'm not aware of a docker image but that would be a great idea. However I'm not sure I understand: why not use `couscous.phar` directly? It doesn't require anything except PHP.

**Comment by bobmulder** [comment]
Well, I needed bower, lesscs and composer (with php requirements). So for users who use docker it would be too hard. It would be awesome to run `docker-compose run couscous preview` instead of loading all needs...

**Comment by mnapoli** [comment]
:+1: I think that goes out of the scope of a default Couscous install, but why not create such image anyway. Feel free to create it and send a pull request to the docs?

**Comment by bobmulder** [comment]
Sounds good... I'll think about it ;) I was curious if something already existed ;)
