### ISSUE TITLE
Unable to use template in git enterprise with two factor

### ISSUE THREAD

**Issue by blee1170** [CouscousPHP/Couscous#177]
I am having a problem storing my template in our internal git enterprise and having other repo's use it. When I do the couscous preview it prompts for my username and password but fails because we also have two factor enabled. 

Is there a way that it can use a git token to pull down the template?

**Comment by blee1170** [comment]
Well I figured out a way passed it. I can use my git username/token in the URL and that works. 

Example:
https://superman:alskdf09823aasfa3@git.example.com/Couscous-template/

**Comment by blee1170** [comment]
I guess it would be nice to pass the username/password as a CLI option, or to have it be a setting in the yaml.

**Comment by cyberbit** [comment]
Does deploying work at all for you? That usually asks me for login credentials, and I have two-factor enabled (on GitHub.com), but it works for me without configuration (with my normal username and password).

**Comment by blee1170** [comment]
Deploying does work for me. But I think it has something to do with my config that I setup a long time ago. It never prompts me when I do a git clone from my command line. Only when Couscous tries to pull down the template. 

It might be something with the user space when the application is running and it cant access my git configs. But I don't know. This would be the next problem I see when I move to automating it with Jenkins.

**Comment by mnapoli** [comment]
Couscous uses the remote URL you used to clone the repository. If you have 2factor enabled you should clone repositories using SSH to avoid authentication prompts.
