### ISSUE TITLE
couscous preview : too many arguments

### ISSUE THREAD

**Issue by WheelyWonka** [CouscousPHP/Couscous#181]
Hi there !

First time with couscous, when i launch `couscous preview ` here's what i get : 

> Generating C:\[...]/.couscous/generated
> [notice] Fetching template from https://github.com/CouscousPHP/Template-Light
> [Couscous\CommandRunner\CommandException]
> Too many arguments.

Tried `couscous preview 0.0.0.0:8000`, same output. Any ideas ?

Thanks !

**Comment by wysow** [comment]
Hello @WheelyWonka and thanks for trying out Couscous!

Can you try using the `-vvv` flag and paste the output here so we can help you with more details?

Thanks.

**Comment by WheelyWonka** [comment]
Sure, here's the output : 

> Generating C:\Users\William Thibault\Desktop\Git\docs to C:\Users\William Thibault\Desktop\Git\docs/.couscous/generated
> [notice] Fetching template from https://github.com/CouscousPHP/Template-Light
>
> [Couscous\CommandRunner\CommandException]
> Too many arguments.
> usage: git clone _[...github documentation...]_
>
> Exception trace:
 () at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\CommandRunner\CommandRunner.php:29
> Couscous\CommandRunner\CommandRunner->run() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\CommandRunner\Git.php:24
> Couscous\CommandRunner\Git->cloneRepository() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\Module\Template\Step\FetchRemoteTemplate.php:78
> Couscous\Module\Template\Step\FetchRemoteTemplate->fetchGitTemplate() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\Module\Template\Step\FetchRemoteTemplate.php:66
> Couscous\Module\Template\Step\FetchRemoteTemplate->__invoke() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\Generator.php:47
> Couscous\Generator->generate() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\Application\Cli\PreviewCommand.php:149
> Couscous\Application\Cli\PreviewCommand->generateWebsite() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\src\Application\Cli\PreviewCommand.php:98
> Couscous\Application\Cli\PreviewCommand->execute() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php:256
> Symfony\Component\Console\Command\Command->run() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\symfony\console\Application.php:820
> Symfony\Component\Console\Application->doRunCommand() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\symfony\console\Application.php:187
> Symfony\Component\Console\Application->doRun() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\symfony\console\Application.php:118
> Symfony\Component\Console\Application->run() at C:\Users\William Thibault\AppData\Roaming\Composer\vendor\couscous\couscous\bin\couscous:43

**Comment by mnapoli** [comment]
Maybe the path is causing issues, it contains a space: `C:\Users\William Thibault\Desktop\Git\docs`

My guess is that [this](https://github.com/CouscousPHP/Couscous/blob/master/src/CommandRunner/Git.php#L24) ends up running this command:

```
git clone https://github.com/CouscousPHP/Template-Light C:\Users\William Thibault\Desktop\Git\docs
```

?

Maybe we should wrap the path with quotes?

**Comment by WheelyWonka** [comment]
Damn... *facepalm* Thanks a lot @mnapoli !
