### ISSUE TITLE
Totally lost: how to configure for github deployment?

### ISSUE THREAD

**Issue by lianhub** [CouscousPHP/Couscous#195]
I am using Couscous in Windows-7.
I read Couscous documentation, but totally lost on Github deployment:
* Why cloning into a stupid TEMP folder?
```
 Cloning into 'cou5FC1.tmp'...
 fatal: 'C:\Users\jerry\AppData\Local\Temp\cou5FC1.tmp' does not appear to be a git repository
 fatal: Could not read from remote repository.
 Please make sure you have the correct access rights
 and the repository exists.
```
* How to configure Github repo, username/password? in couscous.yml?

* Do I have to clone my Github repo first, then work inside this clone?

Thanks!
Jerry

**Comment by mnapoli** [comment]
Hi there, the temp folder is not stupid, please be nice with it :)

Given you opened #196 it seems you made it work, I'll be closing this.

**Comment by lianhub** [comment]
Thanks a lot!

I figured out the working procedure by guessing, it is not that straightforward. So I think the documentation should specify more details.

I was thinking to delete this post, but seems that we can not delete issues in Github, right?

**Comment by mnapoli** [comment]
Nope, that's okay :)
