### ISSUE TITLE
left-menu-bar is not displayed correctly after publishing on Github

### ISSUE THREAD

**Issue by lianhub** [CouscousPHP/Couscous#196]
When I run "couscous preview" and check on: http://127.0.0.1:8000, left-menu-bar is displayed correctly.

But after I "couscous deploy" to Github, left-menu-bar is totally wrong, please check:
              https://lianhub.github.io/test/

what could be the problem?
Thanks!

**Comment by mnapoli** [comment]
Hi @lianhub, it seems you configure an `http://` URL in your config but when deployed it's in `https://`. So the browser blocks loading insecure assets (i.e. the CSS). You can see that in the web developer tools.

I think if you change `http` to `https` it should be fine.

**Comment by lianhub** [comment]
Thanks a lot!

I follows your instructions, and it works well with operations in Linux:
https://lianhub.github.io/try/  (As you see, left-menu-bar displays well.)

However, when I operates in Windows, left-menu-bar gets wrong again. (I may  provide details later in a new issue).

So, do you have a better Couscous revision for windows? Thanks again!

**Comment by mnapoli** [comment]
Have a look at #135, Windows is an issue :/
