### ISSUE TITLE
one step to make template "Light"/"ReadTheDocs" perfect ?

### ISSUE THREAD

**Issue by lianhub** [CouscousPHP/Couscous#198]
I like the demo site: http://gnugat.github.io/redaktilo/doc/01-tutorial.html
* It uses template "Light"
* Unfortunately, you **can NOT click** the index-item to jump on specific section 
 * (For example, you click index "Manipulating a Line", but nothing happen)

So I forked this site: https://lianhub.github.io/day/doc/01-tutorial.html
* I just change to template "ReadTheDocs"
* Now you can click index-item to jump on specific section
* Unfortunately, **indentations** for sub-items disappeared. 

I am new to PHP Twig template.
Can somebody do us a favor to find **a quick solution** on **either** template "Light" **or** "ReadTheDocs"?

Thanks!
Jerry

**Comment by mnapoli** [comment]
Hi, I had a look at https://lianhub.github.io/day/doc/05-extending.html and this is all valid HTML (`ul` inside another `ul`), what you have to do now is CSS to display it however you want to.

There might be specific CSS in "ReadTheDocs" that make the `ul` display like this.

**Comment by lianhub** [comment]
mnapoli:

Thanks for your hint!
I just add my own CSS file: https://lianhub.github.io/day/doc/01-tutorial.html
* Now we see the indentations.
* It is OK for me, but seems ugly than demo: http://gnugat.github.io/redaktilo/doc/01-tutorial.html
* So if we can have click-jump working, I still prefer to the demo.

In order for click-jump to work, I found that we just need to add <id="link-text">: 
* such as: <  id="the-editor">The Editor< />

Do you know how to do it? In twig file, or something else?
Thanks!

Jerry

**Comment by mnapoli** [comment]
Hi, I'm sorry but I can't provide help with HTML or CSS on this issue tracker, this is not related to Couscous and this is notifying a few people that are monitoring this issue tracker.
