### ISSUE TITLE
Copy additional resources

### ISSUE THREAD

**Issue by moqmar** [CouscousPHP/Couscous#206]
Currently it seems like there's no way to include e.g. an image from the source folder, or at least I didn't find it yet. There would be two possibilities:

- Adding a folder, e.g. "assets", which is copied to the output directory, Maybe make this configurable like `includeAssets: ["assets", "images", "..."]`
- Copy all files from folders explicitly mentioned in the `include` configuration option
- Copy all files except for special files like couscous.yml and files/folders in `exclude` (we'd need files there, not just folders)

**Comment by mnapoli** [comment]
Hi there, images are copied though (https://github.com/CouscousPHP/Couscous/blob/master/src/Module/Core/Step/AddImages.php)?

**Comment by moqmar** [comment]
Ah, I see, I tried it with an SVG image. It would be great though to add some kind of configurability to that step, or at least some documentation on what files are copied. SVG is definitely missing in my opinion.

**Comment by mnapoli** [comment]
Feel free to send a pull request to modify this line: https://github.com/CouscousPHP/Couscous/blob/master/src/Module/Core/Step/AddImages.php#L27
