### ISSUE TITLE
section.documentation falls off side of page at size lg

### ISSUE THREAD

**Issue by nklatt** [CouscousPHP/Couscous#211]
On the website, the documentation page (http://couscous.io/docs and below), on wide screens the `section` with class `documentation` is either too wide or has the wrong offset. Need to either change class `col-lg-offset-3` to `col-lg-offset-2` or `col-lg-10` to `col-lg-9`.

**Comment by mnapoli** [comment]
Thank you for the report, would you be able to send a pull request?
