### ISSUE TITLE
Logo + favicon

### ISSUE THREAD

**Issue by mnapoli** [CouscousPHP/Couscous#22]
We need a logo and favicon for the website and the GitHub organization.

**Comment by mnapoli** [comment]
![logo](https://cloud.githubusercontent.com/assets/720328/5609127/cddb2eba-94fc-11e4-83c9-944cc8d2f386.png)

**Comment by mnapoli** [comment]
2 options:

![logo-ccs](https://cloud.githubusercontent.com/assets/720328/5609836/94633ed6-950e-11e4-8d5e-c315cbe55787.png)

![logo-ccs-v2](https://cloud.githubusercontent.com/assets/720328/5609835/8e8ed998-950e-11e4-81d8-2282f48bfb92.png)

I have them in high def, the preview on Github doesn't look really sharp. Any preference?

Created by @climence, open sourced under the Creative Commons license (CC BY 4)

**Comment by lombartec** [comment]
I like the second option more. Thanks @climence :)

**Comment by mnapoli** [comment]
Done!

I've updated the organization logo (https://github.com/CouscousPHP), set the website favicon and uploaded the logo in the repo.

Here is the high-res file: https://github.com/CouscousPHP/Couscous/blob/master/website/logo/logo_big.png
