### ISSUE TITLE
Render Markdown files in unique directories.

### ISSUE THREAD

**Issue by alexfornuto** [CouscousPHP/Couscous#230]
I'm sure this is an easy PEBKAC error but I'm not finding the solution...

in my project directory I have `/docs/git-faq.md`. When I write to the file Couscous notices:

```
1 file(s) changed: regenerating (docs/git-faq.md)
Generating /home/alex/repos/tir to /home/alex/repos/tir/.couscous/generated
```
But when I go to `http://127.0.0.1:8000/docs/git-faq` I get:

>The requested resource /docs/git-faq was not found on this server.

**Comment by alexfornuto** [comment]
Welp.... 

For those who are as stupid as me, you need to specify `.html`. So I suppose my question now is, how do I get each markdown file into its own directory?

**Comment by mnapoli** [comment]
You could write only `README.md` files so those end up as `index.html`. That way you can use directories and skip the `.html` suffix.

(am I correct in my interpretation of your question?)

**Comment by alexfornuto** [comment]
@mnapoli I'd like to avoid making sub-directories for each page.

All my docs currently live in one `/docs/` directory, and are rendered as `/docs/pagename/` by Sculpin:

`permalink: docs/:basename/`

Does Couscous have an equivalent option?

**Comment by mnapoli** [comment]
`/docs/pagename/` is a directory, that's how Sculpin does it.

You could also remove the `.html` suffix from your URLs, e.g. `http://couscous.io/templates` is the same as `http://couscous.io/templates.html`.

But to answer your question no there is no such option in Couscous.

**Comment by alexfornuto** [comment]
>You could also remove the .html suffix from your URLs, e.g. http://couscous.io/templates is the same as http://couscous.io/templates.html.

If that were the case, wouldn't `http://127.0.0.1:8000/docs/git-faq/` load in the preview the way `http://127.0.0.1:8000/docs/git-faq.html` does?

**Comment by mnapoli** [comment]
Yes.

**Comment by alexfornuto** [comment]
It does not, as described above.

**Comment by mnapoli** [comment]
OK maybe it's the built-in PHP server that doesn't support this.

Let's get straight to the point anyway (as we are looping here): that's how Couscous works. I'm sorry but there is no option to customize that.

**Comment by alexfornuto** [comment]
'tis a shame. Couscous seemed like a good option for me, but I think this will be a deal-breaker.
