### ISSUE TITLE
Bootstrap accordion support?

### ISSUE THREAD

**Issue by N6REJ** [CouscousPHP/Couscous#241]
Will this allow bootstrap accordions to function in the docs?

**Comment by mnapoli** [comment]
You can write you own HTML theme, which lets you use any HTML or CSS you want.

**Comment by N6REJ** [comment]
Does the documentation CLEARLY explain how to do that?

**Comment by mnapoli** [comment]
@N6REJ No, because that is not the scope of Couscous. If you want to learn how to use Bootstrap, go read the Bootstrap documentation.

**Comment by N6REJ** [comment]
please don't be flippant.  I understand how to use BS what I DON"T know and it's not covered in the couscous docs, is how to tell couscous to use bootstrap.
You say you can use any html based theme... ok, great... how/where/docs?
