### ISSUE TITLE
Couscous version output

### ISSUE THREAD

**Issue by gmponos** [CouscousPHP/Couscous#243]
When I run
> php bin/couscous.phar --version

 I get
> Console Tool

No version output.

**Comment by mnapoli** [comment]
Hi, this is indeed not supported at the moment. This represents too much effort to hardcode the version in the source code.

Any other solution is welcome, on the condition that it doesn't make the deployment process more complex, that it doesn't introduce too much complexity in the code as well or too many extra Composer dependencies).

**Comment by gmponos** [comment]
The problem now with the phar is that I am not aware of the version installed. Could check hash or something..

One more thing is that I also don't see a changelog.. this could at least indicate which version I am using if it was included in the phar.

**Comment by mnapoli** [comment]
I understand the problem, I have the same problem.

Any contribution that fits the guidelines described above is welcome :)
