### ISSUE TITLE
Allow to change the default configuration file to be loaded

### ISSUE THREAD

**Issue by jdecool** [CouscousPHP/Couscous#267]
Hello,

I use Couscous in some of my projects but I don't the default configuration file `couscous.yml` to be mixed with my others files.

So I want to use another configuration filename, but currently it was impossible to change the configuration to be loaded.

Are you open to a PR that allow this change ?

I imagine something like `couscous generate --configuration-file=, -f`

**Comment by mnapoli** [comment]
Sounds great!
