### ISSUE TITLE
Add documentation for running Couscous in Travis?

### ISSUE THREAD

**Issue by mnapoli** [CouscousPHP/Couscous#34]
Today to generate and deploy Couscous, users have:

- to install Couscous locally
- to run `couscous deploy`

An alternative would be to run Couscous in Travis so that it's redeployed everytime anybody pushes. I'm guessing that can be practical for some projects (no need to have a maintainer that rebuilds the website everytime). Of course we would still keep all the documentation about running Couscous locally.

It could be good to try to set that up for this repository itself, and then add it to the documentation.

**Comment by malukenho** [comment]
@mnapoli it's can be closed, not?

**Comment by mnapoli** [comment]
@malukenho right! Thanks
