### ISSUE TITLE
www.couscous.io leads to domain parked page

### ISSUE THREAD

**Issue by EmiiKhaos** [CouscousPHP/Couscous#54]
www.couscous.io leads to a page, which says the domain is parked. Non www domain works well.

**Comment by markuspoerschke** [comment]
@mnapoli As far as I can see, the domain ist hosted at gandi.net. Isn’t it possible to add a redirect for a sub-domain? https://docs.gandi.net/en/domain_names/common_operations/web_forwarding.html

**Comment by mnapoli** [comment]
Honestly I don't think this is a problem (unless I missed something). I'll be closing this as I don't intend to fix this for now.
