### ISSUE TITLE
Link to current file in GitHub

### ISSUE THREAD

**Issue by mnapoli** [CouscousPHP/Couscous#74]
For wallabag's documentation or PHP-DI too (https://github.com/mnapoli/PHP-DI/issues/132), it would be useful to show "Edit this documentation article" buttons.

To do this, we need to be able to know the name of the current file.

I'm thinking it wouldn't be hard to create a new Markdown step that just sets a metadata variable `currentFile` with the relative filename.

**Comment by mmoreram** [comment]
:+1: Important

**Comment by nicosomb** [comment]
:+1:

**Comment by cyberbit** [comment]
:+1: Definitely would be nice.

**Comment by mnapoli** [comment]
Done in #118! Tested and works, I've added it to http://couscous.io and will be pushing it online shortly!

**Comment by mnapoli** [comment]
Actually sorry it'll be online when 1.3.0 is released ;)

**Comment by mnapoli** [comment]
Released in [1.3.0](https://github.com/CouscousPHP/Couscous/releases/tag/1.3.0).

**Comment by nicosomb** [comment]
Available on our documentation: http://doc.wallabag.org/en/ \o/ Thank you @mnapoli !

**Comment by mnapoli** [comment]
Looks great!

**Comment by cyberbit** [comment]
:+1: Nice!
