### ISSUE TITLE
LiveReload in `couscous preview`

### ISSUE THREAD

**Issue by TamasBarta** [CouscousPHP/Couscous#91]
Modifying a markdown file when `couscous preview` is active, the markdow file modified gets rendered to HTML. It would be nice to notify LiveReload to reload the page in the browser.

**Comment by mnapoli** [comment]
First time I hear about that! That could be interesting indeed if you have time to look into it.

**Comment by TamasBarta** [comment]
Sorry for the late response, I'll take a look. I already found a promising PHP implementation of the LiveReload protocol.

**Comment by bobmulder** [comment]
I am curious about this progress? Any updates?

**Comment by TamasBarta** [comment]
I have to admit, I forgot this. Soon I'll have time, and take a look again, but if it's urgent to you, and you pick this up, we won't be upset, I guess :)

**Comment by bobmulder** [comment]
I'm interested in couscous and looking if I can help somewere... Just curious about your results.... Let me know when you have more information, hopefully I'll be able to join ;)
