### ISSUE TITLE
User and Organization Pages?

### ISSUE THREAD

**Issue by ethanhann** [CouscousPHP/Couscous#94]
User and organization pages are published from master instead of gh-pages. Can Couscous deploy to a branch other than gh-pages?

**Comment by ethanhann** [comment]
Answered my own question. There is an undocumented option for specifying the branch, e.g.
```sh
couscous.phar deploy --branch master
```

**Comment by mnapoli** [comment]
:+1:! Could be added to the documentation indeed, I'll try to keep that in mind.
